Refs #143412 updated pins with changes from generator:
- bumped also postcss to 8.4.5 otherwise when running stylelint fix
  I got the following message:
  TypeError: opts.node.rangeBy is not a function